## Practical 1

## Vectors, matrices, tensors, their manipulation, and basics of OpenCV

In [1]:
# Compose matrix shape and tensor shape
import numpy as np
import keras

In [2]:
# Scalars are 0 dimensional tensors
y = np.array(19)
print("scalar dimension", y.ndim)
print("scalar shape", y.shape)

scalar dimension 0
scalar shape ()


In [3]:
# Vectors are 1 dimensional tensors
y = np.array([19,18,17,16])
print("scalar dimension", y.ndim)
print("scalar shape", y.shape)

scalar dimension 1
scalar shape (4,)


In [4]:
# Matrices are 2 dimensional tensors
y = np.array([[19,18,17,16], [1,2,3,45], [2,4,5,6]])
print("scalar dimension", y.ndim)
print("scalar shape", y.shape)
print(y)

scalar dimension 2
scalar shape (3, 4)
[[19 18 17 16]
 [ 1  2  3 45]
 [ 2  4  5  6]]


In [5]:
# 3 dimensional tensors = tensors
y = np.array([[[19, 18, 17, 16], [1, 2, 3, 45], [2, 4, 5, 6]], [[19, 28, 17, 16], [1, 23, 3, 45], [24, 45, 65, 6]]])
print("scalar dimension", y.ndim)
print("scalar shape", y.shape)
print(y)

scalar dimension 3
scalar shape (2, 3, 4)
[[[19 18 17 16]
  [ 1  2  3 45]
  [ 2  4  5  6]]

 [[19 28 17 16]
  [ 1 23  3 45]
  [24 45 65  6]]]


In [6]:
# Square matrix and inverse:
y = np.array([[1,2], [2,3]])
x = np.linalg.inv(y)
print(y)
print("Inverse of y is", x)

[[1 2]
 [2 3]]
Inverse of y is [[-3.  2.]
 [ 2. -1.]]


In [7]:
z = y*x
print(z)

[[-3.  4.]
 [ 4. -3.]]


In [8]:
import cv2
from keras.datasets import mnist

In [9]:
(imgs_train, lbls_train), (imgs_test, lbls_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [10]:
print(imgs_train.ndim) # images stored as tensors
print(imgs_train.shape) # 60,000 images of 28*28 pixels
print(imgs_train.dtype) # data type for images, can also be double

3
(60000, 28, 28)
uint8


In [11]:
# Get certain part of the dataset i.e., one image
digit = imgs_train[5]
cv2.imwrite("sixth.jpg", digit)

True

In [12]:
# Display that image in another window
cv2.imshow("sixth image", digit)  
cv2.waitKey(0)  
cv2.destroyAllWindows() 

In [13]:
# Deal with only small set of images (slicing the dataset)
new = imgs_train[10:100]
print(new.shape)

(90, 28, 28)


In [14]:
# Modifying (slicing) the pixels of all the images of the dataset 
new = imgs_train[:, 14:, 14:]
print(new.shape)

(60000, 14, 14)


In [15]:
# can also modify the pixels of the image
cv2.imwrite("half_sixth.jpg", imgs_train[5, :, :])

True

In [16]:
# reshape and transpose functions
y = np.array([[0, 1], [1, 2], [2, 3]])
print(y.shape)
print(y)

(3, 2)
[[0 1]
 [1 2]
 [2 3]]


In [17]:
y = y.reshape((6,1))
print(y.shape)
print(y)

(6, 1)
[[0]
 [1]
 [1]
 [2]
 [2]
 [3]]


In [18]:
y = np.transpose(y)
print(y.shape)
print(y)

(1, 6)
[[0 1 1 2 2 3]]
